package com.cisco.cx.osv.dynamodb.entity;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGenerateStrategy;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGenerated;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGenerator;

@DynamoDBAutoGenerated(generator = CustomAutoGeneratedDateTime.Generator.class)
@Retention(RetentionPolicy.RUNTIME)
@Target({ ElementType.FIELD })

public @interface CustomAutoGeneratedDateTime {
	public static class Generator implements DynamoDBAutoGenerator<String> {

		@Override
		public DynamoDBAutoGenerateStrategy getGenerateStrategy() {
			return DynamoDBAutoGenerateStrategy.CREATE;
		}

		@Override
		public final String generate(final String currentValue) {
			
			LocalDateTime instance = LocalDateTime.now();
			DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");
			String formattedString = formatter.format(instance); 
			//System.out.println(formattedString);
			return formattedString.toString();
		}
	}
}