package com.cisco.cx.osv.dynamodb.entity;

import java.io.Serializable;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTypeConvertedEnum;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "osv_schema_migration_audit")
public class SchemaMigrationAudit implements Serializable {

	@DynamoDBHashKey
	@CustomAutoGeneratedDateTime
	private String audit_date; //2022-05-09
	
	@DynamoDBRangeKey
	@CustomAutoGeneratedTimestamp
	private String audit_timestamp; //12:06:29.251
	
	@DynamoDBAttribute
	@DynamoDBAutoGeneratedKey
	@DynamoDBIndexHashKey(globalSecondaryIndexName = "referenceIdGSI")
	private String reference_id;
	
	@DynamoDBAttribute
	@DynamoDBTypeConvertedEnum
	@DynamoDBIndexRangeKey(globalSecondaryIndexName = "referenceIdGSI")
	private LogLevels log_level;

	@DynamoDBAttribute
	@DynamoDBTypeConvertedEnum
	private RequestType request_type;
	
	@DynamoDBAttribute
	private String message;
}
